Milk-V Duo enhancements
riscv/meta-riscv pull request #467
Opened 2024-03-29 14:41 UTC by kinsamanka

This PR replaces the binary-only files provided by the **milkv-duo-bootfiles** recipe.

Improvements over the existing setup:
- mainline OpenSBI (v1.4)
- update u-boot environment variables via `uEnv.txt` file
- change devicetree (dtb) without recompiling the kernel

2024-04-01 17:09 UTC, kraj requested changes
good work, needs few tweaks

2024-04-08 03:07 UTC, kraj commented on recipes-bsp/milkv-duo-fsbl/milkv-duo-fsbl.bb
> +    unset LDFLAGS
please fix tabs vs spaces

2024-04-08 03:08 UTC, kraj commented
I see new commits being added to this pull, which is good, but please mark it as a `draft` PR until you are happy for me to consider it.

2024-04-08 03:20 UTC, kinsamanka commented
The mainline kernel is the last enhancement for this PR, I will set it to draft to iron out any unforeseen bugs. Thanks

2024-05-06 14:52 UTC, kraj approved these changes
lgtm

2024-05-09 05:48 UTC, merged

2024-11-05 16:30 UTC, Mrzhaoqiankun commented
hi Can you give a detailed tutorial